export const allFood = [
  {
    id: 1,
    name: "کوفته برنجی",
    recipe: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
    price: "180,000",
    offPrice: "145,000",
    discount: "35",
    image: "https://s6.uupload.ir/files/koofte-berenji_wjtl.png",
    type: "iranian",
  },
  {
    id: 2,
    name: " کشک بادمجان ",
    recipe:"بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
    price: "210,000",
    offPrice: "203,000",
    discount: "5",
    image: "https://s6.uupload.ir/files/kashke-bademjoon_uji.png",
    type: "iranian",
  },
  {
    id: 3,
    name: " میرزا قاسمی",
    recipe:"بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
    price: "165,000",
    offPrice: "142,500",
    discount: "10",
    image: "https://s6.uupload.ir/files/kalzon_z0y3.png",
    type: "iranian",
  },
  {
    id: 4,
    name: " باقلاقاتوق",
    recipe:"پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
    price: "205,000",
    offPrice: "180,000",
    discount: "30",
    image: "https://s6.uupload.ir/files/baghela_cvpj.png",
    type: "iranian",
  },
  {
    id: 5,
    name: " پاستا سبزیجات",
    recipe:"پاستا، قارچ، گوجه، کدوی خوردشده، پیاز خلالی‌شده",
    price: "175,000",
    offPrice: "140,000",
    discount: "20",
    image: "https://s6.uupload.ir/files/pasta-sabzijat_dqey.png",
    type: "foreign",
  },
  {
    id: 6,
    name: " لازانیا",
    recipe:"لازانیا، قارچ، ریحان تازه، جعفری تازه، گوجه فرنگی، پنیر پیتزا، بادمجان",
    price: "170,000",
    offPrice: "160,000",
    discount: "12",
    image: "https://s6.uupload.ir/files/lasania_9dac.png",
    type: "foreign",
  },
  {
    id: 7,
    name: "سوشی",
    recipe:"جلبک دریایی/ نوری، برنج کته، سرکه سفید (یا سرکه برنج)، شکر، نمک دریا",
    price: "100,000",
    offPrice: "85,000",
    discount: "15",
    image: "https://s6.uupload.ir/files/sushi_nefp.png",
    type: "foreign",
  },
  {
    id: 8,
    name: " پیتزا پپرونی",
    recipe:"تافو، فلفل قرمز خشک شده، پودر دانه‌های خردل، دانه رازیانه، پاپریکا دودی، پودر سیر",
    price: "195,000",
    offPrice: "188,000",
    discount: "12",
    image: "https://s6.uupload.ir/files/pizza_8m9i.png",
    type: "foreign",
  },
];
